### PR TITLE
inlining html5shiv

### PR DESCRIPTION
**Pull request by wheresrhys**
@matthew-andrews @commuterjoy

### CODE REVIEW

**Comment by matthew-andrews** [comment]
you could put it in a document write / put that stuff in assets app?  or is that a worse idea?

**Comment by matthew-andrews** [comment]
[this way non-IE browsers won't get adversely affected by the bigger payload]

**Comment by matthew-andrews** [comment]
but if you want a quick fix this seems fine

**Comment by wheresrhys** [comment]
It's a trade off as that would add a blocking request for ie8. It's only 2k ungzipped (approx 5% of article html size, much less for other pages)

**Pull request merged**
